version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql:latest
    port:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
